[package]
name = "js"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
itoa = "1.0.15"
oxc = { workspace = true }
smallvec = "1.14.0"
thiserror = "2.0.12"

[features]
default = ["debug"]
debug = []
