[package]
name = "html"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc = { workspace = true }
thiserror = "2.0.12"
tl = "0.7.8"
transform = { version = "0.1.0", path = "../transform" }

[lints]
workspace = true
